### DISCUSSION TITLE
Nextjs k8s with a Redis deployement local - help

### DISCUSSION THREAD

**Discussion by erwanriou** [caching-tools/next-shared-cache#463] [Q&A] [answered]
Hey there i am trying to do a quick POC in k8s regarding the cache handle with nextjs 14.1 and the app router but somehow i feel that am doing something wrong.

The redis database is completly empty and i think i probably did something wrong. It's my first time using redis like this and so i am not sure what i did exactly that is wrong. I propose to share all the code did and maybe someone will find out the solution :)

**1. Nextjs**

first the `cache-handler.js`

```js
const { CacheHandler } = require("@neshca/cache-handler")
const createRedisHandler = require("@neshca/cache-handler/redis-stack")
const createLruHandler = require("@neshca/cache-handler/local-lru")
const { createClient } = require("redis")

CacheHandler.onCreation(async () => {
  const client = createClient({ url: process.env.REDIS_URL })
  client.on("error", error => console.error("Redis error:", error.message))

  await client.connect()
  const redisHandler = await createRedisHandler({ client, timeoutMs: 5000 })
  const localHandler = createLruHandler()
  return { handlers: [redisHandler, localHandler] }
})

module.exports = CacheHandler
```

this is quick straight forward, i wouldn't expect an error here hopefully.

my `package.json` have both dependencies in dev and i am currently using nextjs `14.1.4`

```json
{
  "devDependencies": {
    "@neshca/cache-handler": "1.0.8",
    "redis": "4.6.13",
    "sharp": "0.33.2"
  }
}
```
Then my `next.config.js` contain:

```js
const configs = {
  cacheHandler: require.resolve("./cache-handler.js"),
  cacheMaxMemorySize: 0,
  logging: { fetches: { fullUrl: true } },
  // REST
}
```

i am also using the `NEXT_PRIVATE_DEBUG_CACHE` but nothing that could help me there.

**2. Kubernetes**

My `Deployment` and `Service` are very straight forward since its just local. No statefulset or anything fancy (yet)

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-redis
  template:
    metadata:
      labels:
        app: website-redis
    spec:
      containers:
        - name: website-redis
          image: redis/redis-stack:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: website-redis-srv
spec:
  selector:
    app: website-redis
  ports:
    - name: website-redis
      protocol: TCP
      port: 6379
      targetPort: 6379
```

and then the deployment that handle nextjs 

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-website-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-website
  template:
    metadata:
      labels:
        app: client-website
    spec:
      containers:
        - name: client-website
          image: docker.pkg.github.com/my-wesite
          env:
            - name: REDIS_URL
              value: "redis://website-redis-srv:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: client-website-srv
spec:
  selector:
    app: client-website
  ports:
    - name: client-website
      protocol: TCP
      port: 3000
      targetPort: 3000
```

**3. The issue**

The logs on the redis pod show that the redis database seems to have been launched correctly as you can see here:
![Screenshot from 2024-04-11 00-19-07](https://github.com/caching-tools/next-shared-cache/assets/30130006/9b6a076c-3f93-4e73-a6ef-460dfa98d7ed)

And on nextjs side i can see

![Screenshot from 2024-04-11 00-21-36](https://github.com/caching-tools/next-shared-cache/assets/30130006/1e0d0e37-2e3a-44f5-ab94-e8659575508c)

Yet i don't see anymore logs in the redis database and when i try access it with the redis-cli `k exec -it the-redis-pod-name -- redis-cli`
i also dont find anything under `KEYS *`

It seems the redis is completly empty.

**4. Assemption theory**

I suspect that the `REDIS_URL` that am passing as a ref is wrong, i can only see that but i don't know what i did wrong there. As you can see i am using `redis://website-redis-srv:6379` but then maybe this is where i am doing something wrong.

Somehow i don't have any wrong logs about any errors or anything so i am not sure...
I really hope someone can find my issue (it's probably something very stupid)!
